// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HZ9fwSKTrorTPWCfoU8AXIBcUe_ALVE',
    appId: '1:621073247230:web:0beaffd1cb5703bd932eaf',
    messagingSenderId: '621073247230',
    projectId: 'fooddeliverytute-14fc7',
    authDomain: 'fooddeliverytute-14fc7.firebaseapp.com',
    storageBucket: 'fooddeliverytute-14fc7.firebasestorage.app',
    measurementId: 'G-BWWJVVCLR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHcKGW-S2w-2dPEz14JceJfdBT0PkDPaM',
    appId: '1:621073247230:android:30ef644fc8583d63932eaf',
    messagingSenderId: '621073247230',
    projectId: 'fooddeliverytute-14fc7',
    storageBucket: 'fooddeliverytute-14fc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy24GWNQ9EtF4j188RjBrTYPVUyd1pkfE',
    appId: '1:621073247230:ios:c194583e1464baf0932eaf',
    messagingSenderId: '621073247230',
    projectId: 'fooddeliverytute-14fc7',
    storageBucket: 'fooddeliverytute-14fc7.firebasestorage.app',
    iosClientId: '621073247230-ikg7cui2sn8g8frlllhmleq8bcdqu142.apps.googleusercontent.com',
    iosBundleId: 'com.example.famton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy24GWNQ9EtF4j188RjBrTYPVUyd1pkfE',
    appId: '1:621073247230:ios:c194583e1464baf0932eaf',
    messagingSenderId: '621073247230',
    projectId: 'fooddeliverytute-14fc7',
    storageBucket: 'fooddeliverytute-14fc7.firebasestorage.app',
    iosClientId: '621073247230-ikg7cui2sn8g8frlllhmleq8bcdqu142.apps.googleusercontent.com',
    iosBundleId: 'com.example.famton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8HZ9fwSKTrorTPWCfoU8AXIBcUe_ALVE',
    appId: '1:621073247230:web:72a6b27518e6d787932eaf',
    messagingSenderId: '621073247230',
    projectId: 'fooddeliverytute-14fc7',
    authDomain: 'fooddeliverytute-14fc7.firebaseapp.com',
    storageBucket: 'fooddeliverytute-14fc7.firebasestorage.app',
    measurementId: 'G-VVQZZDH419',
  );

}